[package]
name = "zcashrpc-macros"
version = "0.1.0"
authors = ["Gygaxis Vainhardt <gygaxis@zingolabs.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
proc-macro2 = "1.0"
json_typegen = "0.4.1"
