[package]
name = "zcashrpc"
version = "0.1.0"
authors = ["noone <noone@nowhere.net>", "Za <zancas@zingolabs.com>", "Gy <gygaxis@zingolabs.com>"]
edition = "2018"

[workspace]
members = ["zcash_rcli"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "*", features = ["macros"] }
reqwest = { version = "*", features = ["json"] }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
derive_more = "*"
base64 = "*"
eyre = "*"
dirs = { version = "*", optional = true }

[dev-dependencies]
cfg-if = "0.1.10"

[features]
default = ["cookie-finder"]
cookie-finder = ["dirs"]
