name: cargo-test-zcashrpc-typegen

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pull Image
      run: docker pull ghcr.io/zingolabs/zcashrpc:latest

    - name: Clone Quizface
      run: cd .. && git clone https://github.com/zingolabs/quizface.git 

    - name: Run Tests
      run: >- 
       docker run 
       -v /home/runner/work/zcashrpc/zcashrpc:/zcashrpc
       -v /home/runner/work/zcashrpc/quizface:/quizface
       ghcr.io/zingolabs/zcashrpc:latest
       bash -c "mv ./zcash/src/zcash-cli /usr/local/bin/zcash-cli
       && mv ./zcash/src/zcashd /usr/local/bin/zcashd
       && zcashd -daemon
       && cd zcashrpc
       && cargo test
       && cd ../quizface
       && cat lists/passing.txt | xargs cargo run
       && cd ../zcashrpc/zcashrpc-typegen
       && cargo test
       && cargo run ../../quizface/output/v4.3.0_0.2.0
       && cp output/v4.3.0_0.2.0_0.2.0/rpc_response_types.rs ../src/client/subcomponents.rs
       && cd ..
       && cargo test"
