name: cargo-test-zcashrpc-typegen

on:
  pull_request:
    branches: [ master ]
    types: [ assigned, opened, synchronize, reopened ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Debug
      runs: pwd
