name: cargo-test-zcashrpc-typegen

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pull image
      run: docker pull ghcr.io/zingolabs/zcashrpc:latest

    - name: Run Tests
      run:  docker run  -v /home/runner/work/zcashrpc/zcashrpc:/zcashrpc ghcr.io/zingolabs/zcashrpc:latest bash -c "./zcash/src/zcashd -daemon && cd zcashrpc && cargo test --all"
